name: mienv
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10.11
  - numpy=1.26
  - pip
  - pip:
      - torch==2.7.0+cu126
      - torchvision==0.22.0+cu126
      - torchaudio==2.7.0+cu126
      - xformers
      - audiocraft
      - ipython
